//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_PR15_Mebel_Kile2.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SleepAccessories
    {
        public int ID { get; set; }
        public string naimenov { get; set; }
        public decimal cena { get; set; }
        public string BrendID { get; set; }
        public string srokdostavki { get; set; }
        public string TypeID { get; set; }
        public string ColorID { get; set; }
    
        public virtual BrendTable BrendTable { get; set; }
        public virtual ColorTable ColorTable { get; set; }
        public virtual TypeTable TypeTable { get; set; }
    }
}
